// Maio OS data — generated by maio_os_gen.py, do not edit by hand
var MAIO_DATA = {
 "meta": {
  "generatedAt": "2026-10-05",
  "version": "1.0",
  "generator": "maio_os_gen.py",
  "enriched": false
 },
 "stack": [
  {
   "name": "LiteLLM gateway",
   "port": "127.0.0.1:4000",
   "url": "http://127.0.0.1:4000/health/liveliness",
   "code": 200,
   "ms": 7,
   "ok": true,
   "note": "router"
  },
  {
   "name": "MetaMCP",
   "port": "127.0.0.1:12008",
   "url": "http://127.0.0.1:12008/health",
   "code": 200,
   "ms": 9,
   "ok": true,
   "note": "tool hub"
  },
  {
   "name": "Hindsight memory",
   "port": "127.0.0.1:8888",
   "url": "http://127.0.0.1:8888/health",
   "code": 200,
   "ms": 8,
   "ok": true,
   "note": "memory"
  },
  {
   "name": "Hindsight web UI",
   "port": "127.0.0.1:9999",
   "url": "http://127.0.0.1:9999/",
   "code": 200,
   "ms": 44,
   "ok": true,
   "note": "memory ui"
  },
  {
   "name": "oMLX models",
   "port": "127.0.0.1:8000",
   "url": "http://127.0.0.1:8000/v1/models",
   "code": 401,
   "ms": 3,
   "ok": true,
   "note": "401 = auth guard, alive"
  },
  {
   "name": "Ollama",
   "port": "127.0.0.1:11434",
   "url": "http://127.0.0.1:11434/api/tags",
   "code": 200,
   "ms": 38,
   "ok": true,
   "note": "local models"
  },
  {
   "name": "QMD MCP",
   "port": "127.0.0.1:8181",
   "url": "http://127.0.0.1:8181/",
   "code": 404,
   "ms": 1,
   "ok": true,
   "note": "vault search"
  },
  {
   "name": "Gate MCP",
   "port": "127.0.0.1:8792",
   "url": "http://127.0.0.1:8792/",
   "code": 200,
   "ms": 5,
   "ok": true,
   "note": "decision gates"
  }
 ],
 "devServers": [
  {
   "name": "ChromaCommand",
   "url": "http://o3oc10fm2z0gzffee963rmkx.192.168.0.154.sslip.io",
   "code": null,
   "ms": 6,
   "ok": false
  },
  {
   "name": "Divorced Dads",
   "url": "http://x29f5ohoi3vcsb71f3elzfsd.192.168.0.154.sslip.io",
   "code": null,
   "ms": 1,
   "ok": false
  },
  {
   "name": "Esoteric Command",
   "url": "http://j626owap98e8hxudwx6amo02.192.168.0.154.sslip.io",
   "code": null,
   "ms": 1,
   "ok": false
  },
  {
   "name": "GSD Dashboard",
   "url": "http://t5ffr1yc018j0kxd8s8sr4jo.192.168.0.154.sslip.io",
   "code": null,
   "ms": 1,
   "ok": false
  },
  {
   "name": "INFX Web Media",
   "url": "http://gc9d19ckjl9o5xbv7ll0iwu6.192.168.0.154.sslip.io",
   "code": null,
   "ms": 1,
   "ok": false
  },
  {
   "name": "Papa Pasta",
   "url": "http://z51m00l0vfw3erypmwrw7drb.192.168.0.154.sslip.io",
   "code": null,
   "ms": 3,
   "ok": false
  },
  {
   "name": "Personal Site",
   "url": "http://p1aei61r7j1jplux91cx54gp.192.168.0.154.sslip.io",
   "code": null,
   "ms": 1,
   "ok": false
  },
  {
   "name": "Quorum",
   "url": "http://et35kngos0rqjkviatyame9b.192.168.0.154.sslip.io",
   "code": null,
   "ms": 1,
   "ok": false
  },
  {
   "name": "SunScout",
   "url": "http://usolei362859c24hssx15rj8.192.168.0.154.sslip.io",
   "code": null,
   "ms": 1,
   "ok": false
  },
  {
   "name": "Wheel of Life",
   "url": "http://qq1u6zmllgg4xl1oxcyp40mq.192.168.0.154.sslip.io",
   "code": null,
   "ms": 1,
   "ok": false
  }
 ],
 "devServersStaleSince": "2026-10-01T10:49:45Z",
 "reports": [
  {
   "agent": "scrooge",
   "path": "AI-Drive/Agent-Output/scrooge/crypto-play-plan-2026-10-05.html",
   "date": "2026-10-05",
   "ext": "html",
   "kb": 45
  },
  {
   "agent": "research",
   "path": "AI-Drive/Agent-Output/research/crypto-agents-2026-10-11.md",
   "date": "2026-10-05",
   "ext": "md",
   "kb": 28
  },
  {
   "agent": "cmo",
   "path": "AI-Drive/Agent-Output/cmo/crypto-market-snapshot-2026-10-11.md",
   "date": "2026-10-05",
   "ext": "md",
   "kb": 6
  },
  {
   "agent": "cfo",
   "path": "AI-Drive/Agent-Output/cfo/crypto-sa-regulatory-2026-10-11.md",
   "date": "2026-10-05",
   "ext": "md",
   "kb": 26
  },
  {
   "agent": "batman",
   "path": "AI-Drive/Agent-Output/batman/paperclip-setup-2026-10-05.md",
   "date": "2026-10-05",
   "ext": "md",
   "kb": 3
  },
  {
   "agent": "adrianna",
   "path": "AI-Drive/Agent-Output/adrianna/snappier-deploy-2026-10-04/vault-note-v2.md",
   "date": "2026-10-05",
   "ext": "md",
   "kb": 4
  },
  {
   "agent": "xavier",
   "path": "AI-Drive/Agent-Output/xavier/2026-10-04-weekly-score.md",
   "date": "2026-10-04",
   "ext": "md",
   "kb": 9
  },
  {
   "agent": "storm",
   "path": "AI-Drive/Agent-Output/storm/weekly-score-2026-10-04.md",
   "date": "2026-10-04",
   "ext": "md",
   "kb": 7
  },
  {
   "agent": "stack-setup",
   "path": "AI-Drive/Agent-Output/stack-setup/OPEN-ITEMS.md",
   "date": "2026-10-04",
   "ext": "md",
   "kb": 7
  },
  {
   "agent": "splinter",
   "path": "AI-Drive/Agent-Output/splinter/bashar-exercise/bashar-enigmatic-circuit-WEALTH.html",
   "date": "2026-10-04",
   "ext": "html",
   "kb": 289
  },
  {
   "agent": "poppins",
   "path": "AI-Drive/Agent-Output/poppins/2026-10-04-weekly-score.md",
   "date": "2026-10-04",
   "ext": "md",
   "kb": 9
  },
  {
   "agent": "johnny",
   "path": "AI-Drive/Agent-Output/johnny/2026-10-04-weekly-score.md",
   "date": "2026-10-04",
   "ext": "md",
   "kb": 9
  },
  {
   "agent": "jean",
   "path": "AI-Drive/Agent-Output/jean/2026-10-04-weekly-score.md",
   "date": "2026-10-04",
   "ext": "md",
   "kb": 7
  },
  {
   "agent": "courage",
   "path": "AI-Drive/Agent-Output/courage/2026-10-04-stack-health.md",
   "date": "2026-10-04",
   "ext": "md",
   "kb": 13
  },
  {
   "agent": "baymax",
   "path": "AI-Drive/Agent-Output/baymax/2026-10-04-weekly-score.md",
   "date": "2026-10-04",
   "ext": "md",
   "kb": 8
  },
  {
   "agent": "claude",
   "path": "AI-Drive/Agent-Output/claude/Vault-Audit-2026-10-03.md",
   "date": "2026-10-03",
   "ext": "md",
   "kb": 7
  }
 ],
 "projects": [
  {
   "name": "best-town",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/best-town",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-20",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/best-town/index.html",
    "date": "2026-09-20",
    "ext": "html",
    "kb": 659
   }
  },
  {
   "name": "breastfeeding-guide",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/breastfeeding-guide",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-24",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/breastfeeding-guide/index.html",
    "date": "2026-09-24",
    "ext": "html",
    "kb": 257
   }
  },
  {
   "name": "garden-plan",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/garden-plan",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-20",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/garden-plan/index.html",
    "date": "2026-09-20",
    "ext": "html",
    "kb": 44
   }
  },
  {
   "name": "graphify-out",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/graphify-out",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-10-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/graphify-out/cache/stat-index.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 19
   }
  },
  {
   "name": "julie-charts",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/julie-charts",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-12",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/julie-charts/index.html",
    "date": "2026-09-12",
    "ext": "html",
    "kb": 64
   }
  },
  {
   "name": "maio-cosmos",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/maio-cosmos",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-26",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/maio-cosmos/index.html",
    "date": "2026-09-26",
    "ext": "html",
    "kb": 605
   }
  },
  {
   "name": "maio-cosmos-europe",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/maio-cosmos-europe",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-26",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/maio-cosmos-europe/index.html",
    "date": "2026-09-26",
    "ext": "html",
    "kb": 473
   }
  },
  {
   "name": "ricardo-charts",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/ricardo-charts",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-12",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/ricardo-charts/index.html",
    "date": "2026-09-12",
    "ext": "html",
    "kb": 61
   }
  },
  {
   "name": "rj-cosmos",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/rj-cosmos",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-20",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/rj-cosmos/index.html",
    "date": "2026-09-20",
    "ext": "html",
    "kb": 26
   }
  },
  {
   "name": "soul-hotel",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/soul-hotel",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-12",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/soul-hotel/drawings/site-plan.png",
    "date": "2026-09-12",
    "ext": "png",
    "kb": 828
   }
  },
  {
   "name": "tlf-images",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/tlf-images",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-08-17",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/tlf-images/salad-mixed.jpg",
    "date": "2026-08-17",
    "ext": "jpg",
    "kb": 185
   }
  },
  {
   "name": "targetpraks.github.io",
   "family": "dev",
   "root": "DevMini/targetpraks.github.io",
   "what": "GitHub Pages \u2014 Maio OS, charts, reports live here",
   "lastTouched": "2026-10-05",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/maio-os/index.html",
    "date": "2026-10-05",
    "ext": "html",
    "kb": 0
   }
  },
  {
   "name": "Wheel of Life",
   "family": "dev",
   "root": "DevMini/Wheel of Life",
   "what": "wheel-of-life",
   "lastTouched": "2026-10-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/Wheel of Life/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 10
   }
  },
  {
   "name": "chromacommand-platform",
   "family": "dev",
   "root": "DevMini/chromacommand-platform",
   "what": "chromacommand-platform \u2014 Unified RGB + Digital Menu + Audio control platform for Papa Pasta franchise network",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/chromacommand-platform/PRD.md",
    "date": "2026-07-24"
   },
   "artifact": {
    "path": "DevMini/chromacommand-platform/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 23
   }
  },
  {
   "name": "constellation",
   "family": "dev",
   "root": "DevMini/constellation",
   "what": "\u2014",
   "lastTouched": "2026-10-05",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/constellation/constellation/tsconfig.json",
    "date": "2026-10-05",
    "ext": "json",
    "kb": 1
   }
  },
  {
   "name": "esoteric-command",
   "family": "dev",
   "root": "DevMini/esoteric-command",
   "what": "esoteric-command",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/esoteric-command/PRD_FEATURE.md",
    "date": "2026-08-21"
   },
   "artifact": {
    "path": "DevMini/esoteric-command/tsconfig.tsbuildinfo",
    "date": "2026-10-01",
    "ext": "tsbuildinfo",
    "kb": 347
   }
  },
  {
   "name": "gsd-dashboard",
   "family": "dev",
   "root": "DevMini/gsd-dashboard",
   "what": "GSD \u2014 Get Shit Done \u00b7 Limited Edition Dashboard",
   "lastTouched": "2026-10-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/gsd-dashboard/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 1
   }
  },
  {
   "name": "infx-media-website",
   "family": "dev",
   "root": "DevMini/infx-media-website",
   "what": "infx-media",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/infx-media-website/PRD.md",
    "date": "2026-07-24"
   },
   "artifact": {
    "path": "DevMini/infx-media-website/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 11
   }
  },
  {
   "name": "papa-pasta-main-website",
   "family": "dev",
   "root": "DevMini/papa-pasta-main-website",
   "what": "papa-pasta-main-website",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/papa-pasta-main-website/PRD.md",
    "date": "2026-07-24"
   },
   "artifact": {
    "path": "DevMini/papa-pasta-main-website/graphify-out/cache/stat-index.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 89
   }
  },
  {
   "name": "quote-program",
   "family": "dev",
   "root": "DevMini/quote-program",
   "what": "quote-program \u2014 Quorum \u2014 procurement desk. Dev-only tooling for the regression suite; the app itself is a sing",
   "lastTouched": "2026-10-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/quote-program/test-results/.last-run.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 1
   }
  },
  {
   "name": "sa-funding-directory",
   "family": "dev",
   "root": "DevMini/sa-funding-directory",
   "what": "\u2014",
   "lastTouched": "2026-10-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/sa-funding-directory/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 4
   }
  },
  {
   "name": "sunscout",
   "family": "dev",
   "root": "DevMini/sunscout",
   "what": "sunscout",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/sunscout/docs/PRD_v2.md",
    "date": "2026-07-24"
   },
   "artifact": {
    "path": "DevMini/sunscout/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 69
   }
  },
  {
   "name": "sunscout-web",
   "family": "dev",
   "root": "DevMini/sunscout-web",
   "what": "sunscout-web",
   "lastTouched": "2026-09-16",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/sunscout-web/out/_not-found/__next._not-found.txt",
    "date": "2026-09-16",
    "ext": "txt",
    "kb": 1
   }
  },
  {
   "name": "ACDC Express",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/ACDC Express",
   "what": "\u2014",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null
  },
  {
   "name": "Divorced Dads",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Divorced Dads",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Divorced Dads/DD-WORKSPACE-MAP.md",
    "date": "2026-09-01",
    "ext": "md",
    "kb": 3
   }
  },
  {
   "name": "FluxFlow",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/FluxFlow",
   "what": "\u2014",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null
  },
  {
   "name": "HR",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/HR",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/HR/Employment Contracts/INF New Master Permanent Employment contract 3.pdf",
    "date": "2026-09-01",
    "ext": "pdf",
    "kb": 3658
   }
  },
  {
   "name": "INFX Solutions",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/INFX Solutions",
   "what": "\u2014",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null
  },
  {
   "name": "Infinity Brands",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Infinity Brands",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Infinity Brands/Sales-Funnel-Tracker/INF_Sales_Marketing_Funnel_Tracker.xlsx",
    "date": "2026-09-01",
    "ext": "xlsx",
    "kb": 86
   }
  },
  {
   "name": "Papa Pasta",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Papa Pasta",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "AI-Drive/AI-Space/Work/Papa Pasta/Store Design/PRD/PRD-SECTION-DESIGN.md",
    "date": "2026-09-01"
   },
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Papa Pasta/Central Kitchen/Central Kitchen.png",
    "date": "2026-09-01",
    "ext": "png",
    "kb": 1657
   }
  },
  {
   "name": "Quote-Program",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Quote-Program",
   "what": "Quorum (quote-program)",
   "lastTouched": "2026-09-15",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Quote-Program/ui-shots/FINAL-v281-shipped.png",
    "date": "2026-09-15",
    "ext": "png",
    "kb": 393
   }
  },
  {
   "name": "Reels",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Reels",
   "what": "\u2014",
   "lastTouched": "2026-09-10",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Reels/Olympus-Architect-v2/STORYBOARD.md",
    "date": "2026-09-10",
    "ext": "md",
    "kb": 18
   }
  },
  {
   "name": "Soul-Hotel",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Soul-Hotel",
   "what": "\u2014",
   "lastTouched": "2026-09-12",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Soul-Hotel/soul-hotel/drawings/Soul-Hotel-Drawing-Set.pdf",
    "date": "2026-09-12",
    "ext": "pdf",
    "kb": 1814
   }
  },
  {
   "name": "SunScout",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/SunScout",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/SunScout/screenshots/05-trips.png",
    "date": "2026-09-01",
    "ext": "png",
    "kb": 75
   }
  },
  {
   "name": "TLF",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/TLF",
   "what": "\u2014",
   "lastTouched": "2026-08-23",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/TLF/brand/The-Local-Farmer-Investment-Pack-v3.0.pdf",
    "date": "2026-08-23",
    "ext": "pdf",
    "kb": 1005
   }
  },
  {
   "name": "The Local Farmer",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/The Local Farmer",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/The Local Farmer/workstreams/ws-07-inputs/input-supply-strategy.md",
    "date": "2026-09-01",
    "ext": "md",
    "kb": 2
   }
  },
  {
   "name": "_Scratch",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/_Scratch",
   "what": "\u2014",
   "lastTouched": "2026-09-08",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/_Scratch/nova_minimum_net_pricing_v2_3pct.pdf",
    "date": "2026-09-08",
    "ext": "pdf",
    "kb": 133
   }
  },
  {
   "name": "feng-shui",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/feng-shui",
   "what": "\u2014",
   "lastTouched": "2026-08-13",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/feng-shui/51-Trichardt-FengShui.tldraw",
    "date": "2026-08-13",
    "ext": "tldraw",
    "kb": 3177
   }
  },
  {
   "name": "infinity-brands-wiki-backup-phase0",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/infinity-brands-wiki-backup-phase0",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/infinity-brands-wiki-backup-phase0/_retry.html.gz",
    "date": "2026-09-01",
    "ext": "gz",
    "kb": 1
   }
  },
  {
   "name": "model-swap-2026-09-11",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/model-swap-2026-09-11",
   "what": "\u2014",
   "lastTouched": "2026-09-11",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/model-swap-2026-09-11/report.md",
    "date": "2026-09-11",
    "ext": "md",
    "kb": 9
   }
  },
  {
   "name": "task-center-sync-20260901",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/task-center-sync-20260901",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/task-center-sync-20260901/export_task_center.py",
    "date": "2026-09-01",
    "ext": "py",
    "kb": 2
   }
  },
  {
   "name": "tlf-blog-site",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/tlf-blog-site",
   "what": "\u2014",
   "lastTouched": "2026-08-25",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/tlf-blog-site/index.html",
    "date": "2026-08-25",
    "ext": "html",
    "kb": 551
   }
  },
  {
   "name": "zoho_research",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/zoho_research",
   "what": "\u2014",
   "lastTouched": "2026-08-04",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/zoho_research/staff_article.json",
    "date": "2026-08-04",
    "ext": "json",
    "kb": 1
   }
  }
 ],
 "roster": [
  {
   "name": "adrianna",
   "role": "AI-stack chief \u00b7 routes the fleet",
   "latest": {
    "path": "AI-Drive/Agent-Output/adrianna/snappier-deploy-2026-10-04/vault-note-v2.md",
    "date": "2026-10-05"
   }
  },
  {
   "name": "batman",
   "role": "Work family lead",
   "latest": {
    "path": "AI-Drive/Agent-Output/batman/paperclip-setup-2026-10-05.md",
    "date": "2026-10-05"
   }
  },
  {
   "name": "baymax",
   "role": "Weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/baymax/2026-10-04-weekly-score.md",
    "date": "2026-10-04"
   }
  },
  {
   "name": "beast",
   "role": "Vault steward (OpenKnowledge writes)",
   "latest": null
  },
  {
   "name": "builder",
   "role": "Builds",
   "latest": null
  },
  {
   "name": "cao",
   "role": "C-suite \u00b7 analytics",
   "latest": null
  },
  {
   "name": "cfo",
   "role": "C-suite \u00b7 finance",
   "latest": {
    "path": "AI-Drive/Agent-Output/cfo/crypto-sa-regulatory-2026-10-11.md",
    "date": "2026-10-05"
   }
  },
  {
   "name": "cho",
   "role": "C-suite \u00b7 \u2026",
   "latest": null
  },
  {
   "name": "claude",
   "role": "Guest (Claude CLI)",
   "latest": {
    "path": "AI-Drive/Agent-Output/claude/Vault-Audit-2026-10-03.md",
    "date": "2026-10-03"
   }
  },
  {
   "name": "cmo",
   "role": "C-suite \u00b7 marketing",
   "latest": {
    "path": "AI-Drive/Agent-Output/cmo/crypto-market-snapshot-2026-10-11.md",
    "date": "2026-10-05"
   }
  },
  {
   "name": "coo",
   "role": "C-suite \u00b7 operations",
   "latest": null
  },
  {
   "name": "courage",
   "role": "Scheduled jobs & checks",
   "latest": {
    "path": "AI-Drive/Agent-Output/courage/2026-10-04-stack-health.md",
    "date": "2026-10-04"
   }
  },
  {
   "name": "cro",
   "role": "C-suite \u00b7 revenue",
   "latest": null
  },
  {
   "name": "cto",
   "role": "C-suite \u00b7 technology",
   "latest": null
  },
  {
   "name": "dex",
   "role": "Deep research",
   "latest": null
  },
  {
   "name": "dexter",
   "role": "Deep research",
   "latest": null
  },
  {
   "name": "infinity",
   "role": "Infinity Brands",
   "latest": null
  },
  {
   "name": "inspector",
   "role": "Audits & inspection",
   "latest": null
  },
  {
   "name": "jean",
   "role": "Weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/jean/2026-10-04-weekly-score.md",
    "date": "2026-10-04"
   }
  },
  {
   "name": "johnny",
   "role": "Weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/johnny/2026-10-04-weekly-score.md",
    "date": "2026-10-04"
   }
  },
  {
   "name": "lois",
   "role": "Ticker",
   "latest": null
  },
  {
   "name": "papa",
   "role": "Papa Pasta business",
   "latest": null
  },
  {
   "name": "poppins",
   "role": "Weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/poppins/2026-10-04-weekly-score.md",
    "date": "2026-10-04"
   }
  },
  {
   "name": "research",
   "role": "Research arm",
   "latest": {
    "path": "AI-Drive/Agent-Output/research/crypto-agents-2026-10-11.md",
    "date": "2026-10-05"
   }
  },
  {
   "name": "reviewer",
   "role": "Code review",
   "latest": null
  },
  {
   "name": "scrooge",
   "role": "Money \u00b7 crypto wheels",
   "latest": {
    "path": "AI-Drive/Agent-Output/scrooge/crypto-play-plan-2026-10-05.html",
    "date": "2026-10-05"
   }
  },
  {
   "name": "shadow",
   "role": "After-dark family",
   "latest": null
  },
  {
   "name": "splinter",
   "role": "Personal family lead",
   "latest": {
    "path": "AI-Drive/Agent-Output/splinter/bashar-exercise/bashar-enigmatic-circuit-WEALTH.html",
    "date": "2026-10-04"
   }
  },
  {
   "name": "stack-setup",
   "role": "Stack installs",
   "latest": {
    "path": "AI-Drive/Agent-Output/stack-setup/OPEN-ITEMS.md",
    "date": "2026-10-04"
   }
  },
  {
   "name": "storm",
   "role": "Weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/storm/weekly-score-2026-10-04.md",
    "date": "2026-10-04"
   }
  },
  {
   "name": "xavier",
   "role": "Weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/xavier/2026-10-04-weekly-score.md",
    "date": "2026-10-04"
   }
  }
 ],
 "prds": [
  {
   "title": "PRD-SECTION-DESIGN.md",
   "project": "Papa Pasta",
   "path": "AI-Drive/AI-Space/Work/Papa Pasta/Store Design/PRD/PRD-SECTION-DESIGN.md",
   "date": "2026-09-01"
  },
  {
   "title": "PRD_FEATURE.md",
   "project": "esoteric-command",
   "path": "DevMini/esoteric-command/PRD_FEATURE.md",
   "date": "2026-08-21"
  },
  {
   "title": "PRD.md",
   "project": "chromacommand-platform",
   "path": "DevMini/chromacommand-platform/PRD.md",
   "date": "2026-07-24"
  },
  {
   "title": "PRD.md",
   "project": "infx-media-website",
   "path": "DevMini/infx-media-website/PRD.md",
   "date": "2026-07-24"
  },
  {
   "title": "PRD.md",
   "project": "papa-pasta-main-website",
   "path": "DevMini/papa-pasta-main-website/PRD.md",
   "date": "2026-07-24"
  },
  {
   "title": "PRD_v2.md",
   "project": "sunscout",
   "path": "DevMini/sunscout/docs/PRD_v2.md",
   "date": "2026-07-24"
  }
 ],
 "summary": {
  "stackLive": 8,
  "stackTotal": 8,
  "devOnline": 0,
  "devTotal": 10,
  "projects": 43,
  "reports": 16,
  "roster": 31,
  "prds": 6
 }
};
