// Maio OS data — generated by maio_os_gen.py, do not edit by hand
var MAIO_DATA = {
 "meta": {
  "generatedAt": "2026-10-09",
  "version": "2.0",
  "generator": "maio_os_gen.py",
  "enriched": true
 },
 "stack": [
  {
   "name": "LiteLLM gateway",
   "port": "127.0.0.1:4000",
   "url": "http://127.0.0.1:4000/health/liveliness",
   "code": 200,
   "ms": 14,
   "ok": true,
   "note": "router"
  },
  {
   "name": "MetaMCP",
   "port": "127.0.0.1:12008",
   "url": "http://127.0.0.1:12008/health",
   "code": 200,
   "ms": 8,
   "ok": true,
   "note": "tool hub"
  },
  {
   "name": "Hindsight memory",
   "port": "127.0.0.1:8888",
   "url": "http://127.0.0.1:8888/health",
   "code": 200,
   "ms": 6,
   "ok": true,
   "note": "memory"
  },
  {
   "name": "Hindsight web UI",
   "port": "127.0.0.1:9999",
   "url": "http://127.0.0.1:9999/",
   "code": 200,
   "ms": 117,
   "ok": true,
   "note": "memory ui"
  },
  {
   "name": "oMLX models",
   "port": "127.0.0.1:8000",
   "url": "http://127.0.0.1:8000/v1/models",
   "code": 401,
   "ms": 2,
   "ok": true,
   "note": "401 = auth guard, alive"
  },
  {
   "name": "Ollama",
   "port": "127.0.0.1:11434",
   "url": "http://127.0.0.1:11434/api/tags",
   "code": 200,
   "ms": 43,
   "ok": true,
   "note": "local models"
  },
  {
   "name": "QMD MCP",
   "port": "127.0.0.1:8181",
   "url": "http://127.0.0.1:8181/",
   "code": 404,
   "ms": 1,
   "ok": true,
   "note": "vault search"
  },
  {
   "name": "Gate MCP",
   "port": "127.0.0.1:8792",
   "url": "http://127.0.0.1:8792/",
   "code": 200,
   "ms": 0,
   "ok": true,
   "note": "decision gates"
  },
  {
   "name": "Hermes dashboard",
   "port": "127.0.0.1:9110",
   "url": "http://127.0.0.1:9110/",
   "code": 200,
   "ms": 17,
   "ok": true,
   "note": "kanban + sessions UI"
  },
  {
   "name": "Paperclip",
   "port": "127.0.0.1:3100",
   "url": "http://127.0.0.1:3100/",
   "code": 200,
   "ms": 17,
   "ok": true,
   "note": "company control plane"
  },
  {
   "name": "Snappier",
   "port": "127.0.0.1:8800",
   "url": "http://127.0.0.1:8800/",
   "code": 200,
   "ms": 5,
   "ok": true,
   "note": "IPTV server"
  },
  {
   "name": "Omnigent",
   "port": "127.0.0.1:6767",
   "url": "http://127.0.0.1:6767/",
   "code": 200,
   "ms": 18,
   "ok": true,
   "note": "agent host"
  }
 ],
 "devServers": [
  {
   "name": "ChromaCommand",
   "url": "http://o3oc10fm2z0gzffee963rmkx.192.168.0.154.sslip.io",
   "code": null,
   "ms": 1141,
   "ok": false
  },
  {
   "name": "Divorced Dads",
   "url": "http://x29f5ohoi3vcsb71f3elzfsd.192.168.0.154.sslip.io",
   "code": null,
   "ms": 190,
   "ok": false
  },
  {
   "name": "Esoteric Command",
   "url": "http://j626owap98e8hxudwx6amo02.192.168.0.154.sslip.io",
   "code": null,
   "ms": 192,
   "ok": false
  },
  {
   "name": "GSD Dashboard",
   "url": "http://t5ffr1yc018j0kxd8s8sr4jo.192.168.0.154.sslip.io",
   "code": null,
   "ms": 193,
   "ok": false
  },
  {
   "name": "INFX Web Media",
   "url": "http://gc9d19ckjl9o5xbv7ll0iwu6.192.168.0.154.sslip.io",
   "code": null,
   "ms": 193,
   "ok": false
  },
  {
   "name": "Papa Pasta",
   "url": "http://z51m00l0vfw3erypmwrw7drb.192.168.0.154.sslip.io",
   "code": null,
   "ms": 192,
   "ok": false
  },
  {
   "name": "Personal Site",
   "url": "http://p1aei61r7j1jplux91cx54gp.192.168.0.154.sslip.io",
   "code": null,
   "ms": 192,
   "ok": false
  },
  {
   "name": "Quorum",
   "url": "http://et35kngos0rqjkviatyame9b.192.168.0.154.sslip.io",
   "code": null,
   "ms": 190,
   "ok": false
  },
  {
   "name": "SunScout",
   "url": "http://usolei362859c24hssx15rj8.192.168.0.154.sslip.io",
   "code": null,
   "ms": 192,
   "ok": false
  },
  {
   "name": "Wheel of Life",
   "url": "http://qq1u6zmllgg4xl1oxcyp40mq.192.168.0.154.sslip.io",
   "code": null,
   "ms": 193,
   "ok": false
  }
 ],
 "devServersStaleSince": "2026-10-01T10:49:45Z",
 "reports": [
  {
   "agent": "courage",
   "path": "AI-Drive/Agent-Output/courage/.watchtower-probe",
   "date": "2026-10-09",
   "ext": "",
   "kb": 1
  },
  {
   "agent": "adrianna",
   "path": "AI-Drive/Agent-Output/adrianna/maio-os-scout-merge.json",
   "date": "2026-10-09",
   "ext": "json",
   "kb": 15
  },
  {
   "agent": "splinter",
   "path": "AI-Drive/Agent-Output/splinter/published.csv",
   "date": "2026-10-08",
   "ext": "csv",
   "kb": 1
  },
  {
   "agent": "research",
   "path": "AI-Drive/Agent-Output/research/agent-sector-ledger.csv",
   "date": "2026-10-08",
   "ext": "csv",
   "kb": 1
  },
  {
   "agent": "dexter",
   "path": "AI-Drive/Agent-Output/dexter/metrics/spend-daily.csv",
   "date": "2026-10-08",
   "ext": "csv",
   "kb": 1
  },
  {
   "agent": "beast",
   "path": "AI-Drive/Agent-Output/beast/probe-write-t_a06880c2.txt",
   "date": "2026-10-08",
   "ext": "txt",
   "kb": 1
  },
  {
   "agent": "batman",
   "path": "AI-Drive/Agent-Output/batman/2026-10-08-cliq-sales-marketing-fill-form-order-v2.html",
   "date": "2026-10-08",
   "ext": "html",
   "kb": 27
  },
  {
   "agent": "xavier",
   "path": "AI-Drive/Agent-Output/xavier/2026-10-07-weekly-score.md",
   "date": "2026-10-07",
   "ext": "md",
   "kb": 12
  },
  {
   "agent": "targetpraks",
   "path": "AI-Drive/Agent-Output/targetpraks/github-public-audit/visibility-change-send.txt",
   "date": "2026-10-07",
   "ext": "txt",
   "kb": 1
  },
  {
   "agent": "storm",
   "path": "AI-Drive/Agent-Output/storm/weekly-score-2026-10-07.md",
   "date": "2026-10-07",
   "ext": "md",
   "kb": 10
  },
  {
   "agent": "scrooge",
   "path": "AI-Drive/Agent-Output/scrooge/weekly-score-2026-10-07.md",
   "date": "2026-10-07",
   "ext": "md",
   "kb": 15
  },
  {
   "agent": "reviewer",
   "path": "AI-Drive/Agent-Output/reviewer/published.csv",
   "date": "2026-10-07",
   "ext": "csv",
   "kb": 2
  },
  {
   "agent": "poppins",
   "path": "AI-Drive/Agent-Output/poppins/2026-10-07-weekly-score.md",
   "date": "2026-10-07",
   "ext": "md",
   "kb": 17
  },
  {
   "agent": "johnny",
   "path": "AI-Drive/Agent-Output/johnny/2026-10-07-weekly-score.md",
   "date": "2026-10-07",
   "ext": "md",
   "kb": 9
  },
  {
   "agent": "jean",
   "path": "AI-Drive/Agent-Output/jean/2026-10-11-weekly-score.md",
   "date": "2026-10-07",
   "ext": "md",
   "kb": 9
  },
  {
   "agent": "inspector",
   "path": "AI-Drive/Agent-Output/inspector/hindsight-dashboard-recon-2026-10-07.md",
   "date": "2026-10-07",
   "ext": "md",
   "kb": 14
  },
  {
   "agent": "builder",
   "path": "AI-Drive/Agent-Output/builder/published.csv",
   "date": "2026-10-07",
   "ext": "csv",
   "kb": 3
  },
  {
   "agent": "baymax",
   "path": "AI-Drive/Agent-Output/baymax/2026-10-07-paba-grey-hair-assessment.md",
   "date": "2026-10-07",
   "ext": "md",
   "kb": 49
  },
  {
   "agent": "stack-setup",
   "path": "AI-Drive/Agent-Output/stack-setup/skills-ledger.md",
   "date": "2026-10-06",
   "ext": "md",
   "kb": 5
  },
  {
   "agent": "papa",
   "path": "AI-Drive/Agent-Output/papa/deep-dive-work/comment-verification.json",
   "date": "2026-10-06",
   "ext": "json",
   "kb": 15
  },
  {
   "agent": "bruce-wayne",
   "path": "AI-Drive/Agent-Output/bruce-wayne/constellation-audit-2026-10-06/CARD.md",
   "date": "2026-10-06",
   "ext": "md",
   "kb": 11
  },
  {
   "agent": "cmo",
   "path": "AI-Drive/Agent-Output/cmo/crypto-market-snapshot-2026-10-11.md",
   "date": "2026-10-05",
   "ext": "md",
   "kb": 6
  },
  {
   "agent": "cfo",
   "path": "AI-Drive/Agent-Output/cfo/crypto-sa-regulatory-2026-10-11.md",
   "date": "2026-10-05",
   "ext": "md",
   "kb": 26
  },
  {
   "agent": "claude",
   "path": "AI-Drive/Agent-Output/claude/Vault-Audit-2026-10-03.md",
   "date": "2026-10-03",
   "ext": "md",
   "kb": 7
  }
 ],
 "projects": [
  {
   "name": "best-town",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/best-town",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-20",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/best-town/index.html",
    "date": "2026-09-20",
    "ext": "html",
    "kb": 659
   }
  },
  {
   "name": "breastfeeding-guide",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/breastfeeding-guide",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-24",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/breastfeeding-guide/index.html",
    "date": "2026-09-24",
    "ext": "html",
    "kb": 257
   }
  },
  {
   "name": "garden-plan",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/garden-plan",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-20",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/garden-plan/index.html",
    "date": "2026-09-20",
    "ext": "html",
    "kb": 44
   }
  },
  {
   "name": "graphify-out",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/graphify-out",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-10-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/graphify-out/cache/stat-index.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 19
   }
  },
  {
   "name": "julie-charts",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/julie-charts",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-12",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/julie-charts/index.html",
    "date": "2026-09-12",
    "ext": "html",
    "kb": 64
   }
  },
  {
   "name": "maio-cosmos",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/maio-cosmos",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-26",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/maio-cosmos/index.html",
    "date": "2026-09-26",
    "ext": "html",
    "kb": 605
   }
  },
  {
   "name": "maio-cosmos-europe",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/maio-cosmos-europe",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-26",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/maio-cosmos-europe/index.html",
    "date": "2026-09-26",
    "ext": "html",
    "kb": 473
   }
  },
  {
   "name": "ricardo-charts",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/ricardo-charts",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-12",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/ricardo-charts/index.html",
    "date": "2026-09-12",
    "ext": "html",
    "kb": 61
   }
  },
  {
   "name": "rj-cosmos",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/rj-cosmos",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-20",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/rj-cosmos/index.html",
    "date": "2026-09-20",
    "ext": "html",
    "kb": 26
   }
  },
  {
   "name": "soul-hotel",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/soul-hotel",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-09-12",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/soul-hotel/drawings/site-plan.png",
    "date": "2026-09-12",
    "ext": "png",
    "kb": 828
   }
  },
  {
   "name": "tlf-images",
   "family": "pages",
   "root": "DevMini/targetpraks.github.io/tlf-images",
   "what": "Live page on targetpraks.github.io",
   "lastTouched": "2026-08-17",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/tlf-images/salad-mixed.jpg",
    "date": "2026-08-17",
    "ext": "jpg",
    "kb": 185
   }
  },
  {
   "name": "targetpraks.github.io",
   "family": "dev",
   "root": "DevMini/targetpraks.github.io",
   "what": "GitHub Pages \u2014 Maio OS, charts, reports live here",
   "lastTouched": "2026-10-08",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/targetpraks.github.io/cliq-sales-marketing-fill-form-order.html",
    "date": "2026-10-08",
    "ext": "html",
    "kb": 0
   }
  },
  {
   "name": "Wheel of Life",
   "family": "dev",
   "root": "DevMini/Wheel of Life",
   "what": "wheel-of-life",
   "lastTouched": "2026-10-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/Wheel of Life/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 10
   }
  },
  {
   "name": "chromacommand-platform",
   "family": "dev",
   "root": "DevMini/chromacommand-platform",
   "what": "chromacommand-platform \u2014 Unified RGB + Digital Menu + Audio control platform for Papa Pasta franchise network",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/chromacommand-platform/PRD.md",
    "date": "2026-07-24"
   },
   "artifact": {
    "path": "DevMini/chromacommand-platform/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 23
   }
  },
  {
   "name": "constellation",
   "family": "dev",
   "root": "DevMini/constellation",
   "what": "\u2014",
   "lastTouched": "2026-10-08",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/constellation/constellation/tsconfig.json",
    "date": "2026-10-08",
    "ext": "json",
    "kb": 1
   }
  },
  {
   "name": "esoteric-command",
   "family": "dev",
   "root": "DevMini/esoteric-command",
   "what": "esoteric-command",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/esoteric-command/PRD_FEATURE.md",
    "date": "2026-08-21"
   },
   "artifact": {
    "path": "DevMini/esoteric-command/tsconfig.tsbuildinfo",
    "date": "2026-10-01",
    "ext": "tsbuildinfo",
    "kb": 347
   }
  },
  {
   "name": "gsd-dashboard",
   "family": "dev",
   "root": "DevMini/gsd-dashboard",
   "what": "GSD \u2014 Get Shit Done \u00b7 Limited Edition Dashboard",
   "lastTouched": "2026-10-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/gsd-dashboard/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 1
   }
  },
  {
   "name": "infx-media-website",
   "family": "dev",
   "root": "DevMini/infx-media-website",
   "what": "infx-media",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/infx-media-website/PRD.md",
    "date": "2026-07-24"
   },
   "artifact": {
    "path": "DevMini/infx-media-website/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 11
   }
  },
  {
   "name": "maio-tools",
   "family": "dev",
   "root": "DevMini/maio-tools",
   "what": "maio-tools",
   "lastTouched": "2026-10-08",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/maio-tools/instructions/document-publishing-block.md",
    "date": "2026-10-08",
    "ext": "md",
    "kb": 1
   }
  },
  {
   "name": "papa-pasta-main-website",
   "family": "dev",
   "root": "DevMini/papa-pasta-main-website",
   "what": "papa-pasta-main-website",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/papa-pasta-main-website/PRD.md",
    "date": "2026-07-24"
   },
   "artifact": {
    "path": "DevMini/papa-pasta-main-website/graphify-out/cache/stat-index.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 89
   }
  },
  {
   "name": "quote-program",
   "family": "dev",
   "root": "DevMini/quote-program",
   "what": "quote-program \u2014 Quorum \u2014 procurement desk. Dev-only tooling for the regression suite; the app itself is a sing",
   "lastTouched": "2026-10-06",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/quote-program/test-results/.last-run.json",
    "date": "2026-10-06",
    "ext": "json",
    "kb": 1
   }
  },
  {
   "name": "sa-funding-directory",
   "family": "dev",
   "root": "DevMini/sa-funding-directory",
   "what": "\u2014",
   "lastTouched": "2026-10-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/sa-funding-directory/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 4
   }
  },
  {
   "name": "sunscout",
   "family": "dev",
   "root": "DevMini/sunscout",
   "what": "sunscout",
   "lastTouched": "2026-10-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "DevMini/sunscout/docs/PRD_v2.md",
    "date": "2026-07-24"
   },
   "artifact": {
    "path": "DevMini/sunscout/graphify-out/manifest.json",
    "date": "2026-10-01",
    "ext": "json",
    "kb": 69
   }
  },
  {
   "name": "sunscout-web",
   "family": "dev",
   "root": "DevMini/sunscout-web",
   "what": "sunscout-web",
   "lastTouched": "2026-09-16",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "DevMini/sunscout-web/out/_not-found/__next._not-found.txt",
    "date": "2026-09-16",
    "ext": "txt",
    "kb": 1
   }
  },
  {
   "name": "ACDC Express",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/ACDC Express",
   "what": "\u2014",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null
  },
  {
   "name": "Divorced Dads",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Divorced Dads",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Divorced Dads/DD-WORKSPACE-MAP.md",
    "date": "2026-09-01",
    "ext": "md",
    "kb": 3
   }
  },
  {
   "name": "FluxFlow",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/FluxFlow",
   "what": "\u2014",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null
  },
  {
   "name": "HR",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/HR",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/HR/Employment Contracts/INF New Master Permanent Employment contract 3.pdf",
    "date": "2026-09-01",
    "ext": "pdf",
    "kb": 3658
   }
  },
  {
   "name": "INFX Solutions",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/INFX Solutions",
   "what": "\u2014",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null
  },
  {
   "name": "Infinity Brands",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Infinity Brands",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Infinity Brands/Sales-Funnel-Tracker/INF_Sales_Marketing_Funnel_Tracker.xlsx",
    "date": "2026-09-01",
    "ext": "xlsx",
    "kb": 86
   }
  },
  {
   "name": "Papa Pasta",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Papa Pasta",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": true,
   "prdNewest": {
    "path": "AI-Drive/AI-Space/Work/Papa Pasta/Store Design/PRD/PRD-SECTION-DESIGN.md",
    "date": "2026-09-01"
   },
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Papa Pasta/Central Kitchen/Central Kitchen.png",
    "date": "2026-09-01",
    "ext": "png",
    "kb": 1657
   }
  },
  {
   "name": "Quote-Program",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Quote-Program",
   "what": "Quorum (quote-program)",
   "lastTouched": "2026-09-15",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Quote-Program/ui-shots/FINAL-v281-shipped.png",
    "date": "2026-09-15",
    "ext": "png",
    "kb": 393
   }
  },
  {
   "name": "Reels",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Reels",
   "what": "\u2014",
   "lastTouched": "2026-09-10",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Reels/Olympus-Architect-v2/STORYBOARD.md",
    "date": "2026-09-10",
    "ext": "md",
    "kb": 18
   }
  },
  {
   "name": "Soul-Hotel",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/Soul-Hotel",
   "what": "\u2014",
   "lastTouched": "2026-09-12",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/Soul-Hotel/soul-hotel/drawings/Soul-Hotel-Drawing-Set.pdf",
    "date": "2026-09-12",
    "ext": "pdf",
    "kb": 1814
   }
  },
  {
   "name": "SunScout",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/SunScout",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/SunScout/screenshots/05-trips.png",
    "date": "2026-09-01",
    "ext": "png",
    "kb": 75
   }
  },
  {
   "name": "TLF",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/TLF",
   "what": "\u2014",
   "lastTouched": "2026-08-23",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/TLF/brand/The-Local-Farmer-Investment-Pack-v3.0.pdf",
    "date": "2026-08-23",
    "ext": "pdf",
    "kb": 1005
   }
  },
  {
   "name": "The Local Farmer",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/The Local Farmer",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/The Local Farmer/workstreams/ws-07-inputs/input-supply-strategy.md",
    "date": "2026-09-01",
    "ext": "md",
    "kb": 2
   }
  },
  {
   "name": "_Scratch",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/_Scratch",
   "what": "\u2014",
   "lastTouched": "2026-09-08",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/_Scratch/nova_minimum_net_pricing_v2_3pct.pdf",
    "date": "2026-09-08",
    "ext": "pdf",
    "kb": 133
   }
  },
  {
   "name": "feng-shui",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/feng-shui",
   "what": "\u2014",
   "lastTouched": "2026-08-13",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/feng-shui/51-Trichardt-FengShui.tldraw",
    "date": "2026-08-13",
    "ext": "tldraw",
    "kb": 3177
   }
  },
  {
   "name": "infinity-brands-wiki-backup-phase0",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/infinity-brands-wiki-backup-phase0",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/infinity-brands-wiki-backup-phase0/_retry.html.gz",
    "date": "2026-09-01",
    "ext": "gz",
    "kb": 1
   }
  },
  {
   "name": "model-swap-2026-09-11",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/model-swap-2026-09-11",
   "what": "\u2014",
   "lastTouched": "2026-09-11",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/model-swap-2026-09-11/report.md",
    "date": "2026-09-11",
    "ext": "md",
    "kb": 9
   }
  },
  {
   "name": "task-center-sync-20260901",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/task-center-sync-20260901",
   "what": "\u2014",
   "lastTouched": "2026-09-01",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/task-center-sync-20260901/export_task_center.py",
    "date": "2026-09-01",
    "ext": "py",
    "kb": 2
   }
  },
  {
   "name": "tlf-blog-site",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/tlf-blog-site",
   "what": "\u2014",
   "lastTouched": "2026-08-25",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/tlf-blog-site/index.html",
    "date": "2026-08-25",
    "ext": "html",
    "kb": 551
   }
  },
  {
   "name": "zoho_research",
   "family": "work",
   "root": "AI-Drive/AI-Space/Work/zoho_research",
   "what": "\u2014",
   "lastTouched": "2026-08-04",
   "hasPRD": false,
   "prdNewest": null,
   "artifact": {
    "path": "AI-Drive/AI-Space/Work/zoho_research/staff_article.json",
    "date": "2026-08-04",
    "ext": "json",
    "kb": 1
   }
  },
  {
   "name": "Papa Pasta",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "QSR Franchise \u2014 pasta",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "1 \u2014 \"100% my main priority\"",
   "status": "Active Development"
  },
  {
   "name": "The Local Farmer",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "Farm / Supply, micro-franchise",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "2",
   "status": "Active"
  },
  {
   "name": "Divorced Dads",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "App for Divorced Men / Family Law Tech",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "3",
   "status": "Active Development"
  },
  {
   "name": "Infinity Brands",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "Brand / Portfolio Company (HQ)",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "4",
   "status": "Active"
  },
  {
   "name": "INFX Solutions",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "Zoho Implementation / Business Digitization",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "5",
   "status": "Active"
  },
  {
   "name": "INFX Media",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "Media / Marketing",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "6",
   "status": "Active Development"
  },
  {
   "name": "INFX Labs",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "Software Development House",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "6",
   "status": "Active"
  },
  {
   "name": "FluxFlow",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "ETL + Agentic AI for Business Tools",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "6",
   "status": "Active Development"
  },
  {
   "name": "ChromaCommand",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "RGB / digital menu / audio for the Papa Pasta network",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "6",
   "status": "Active Development"
  },
  {
   "name": "SunScout",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "Beach Convenience App (may become BeachScout)",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "6",
   "status": "Active Development"
  },
  {
   "name": "Loxbox",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "TBD (Greek market)",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "6",
   "status": "Fundraising"
  },
  {
   "name": "Soul Hotel",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "Hospitality / Apartment Hotel, Rhodes, Greece",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "7",
   "status": "Concept"
  },
  {
   "name": "ACDC Express",
   "family": "venture",
   "root": "see Business-Index.md (vault)",
   "what": "Electrical Retail / Franchise",
   "lastTouched": null,
   "hasPRD": false,
   "prdNewest": null,
   "artifact": null,
   "priority": "7",
   "status": "Active"
  }
 ],
 "roster": [
  {
   "name": "adrianna",
   "role": "AI-stack chief \u00b7 routes the fleet",
   "latest": {
    "path": "AI-Drive/Agent-Output/adrianna/maio-os-scout-merge.json",
    "date": "2026-10-09"
   }
  },
  {
   "name": "batman",
   "role": "Work family lead",
   "latest": {
    "path": "AI-Drive/Agent-Output/batman/2026-10-08-cliq-sales-marketing-fill-form-order-v2.html",
    "date": "2026-10-08"
   }
  },
  {
   "name": "baymax",
   "role": "Fitness & wellness \u00b7 weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/baymax/2026-10-07-paba-grey-hair-assessment.md",
    "date": "2026-10-07"
   }
  },
  {
   "name": "beast",
   "role": "Vault steward \u2014 hygiene & lifecycle",
   "latest": {
    "path": "AI-Drive/Agent-Output/beast/probe-write-t_a06880c2.txt",
    "date": "2026-10-08"
   }
  },
  {
   "name": "bruce-wayne",
   "role": "\u2014",
   "latest": {
    "path": "AI-Drive/Agent-Output/bruce-wayne/constellation-audit-2026-10-06/CARD.md",
    "date": "2026-10-06"
   }
  },
  {
   "name": "builder",
   "role": "Builds feature work & PRs",
   "latest": {
    "path": "AI-Drive/Agent-Output/builder/published.csv",
    "date": "2026-10-07"
   }
  },
  {
   "name": "cao",
   "role": "C-suite \u00b7 analytics",
   "latest": null
  },
  {
   "name": "cfo",
   "role": "C-suite \u00b7 finance",
   "latest": {
    "path": "AI-Drive/Agent-Output/cfo/crypto-sa-regulatory-2026-10-11.md",
    "date": "2026-10-05"
   }
  },
  {
   "name": "cho",
   "role": "C-suite \u00b7 \u2026",
   "latest": null
  },
  {
   "name": "claude",
   "role": "Guest (Claude CLI)",
   "latest": {
    "path": "AI-Drive/Agent-Output/claude/Vault-Audit-2026-10-03.md",
    "date": "2026-10-03"
   }
  },
  {
   "name": "cmo",
   "role": "C-suite \u00b7 marketing",
   "latest": {
    "path": "AI-Drive/Agent-Output/cmo/crypto-market-snapshot-2026-10-11.md",
    "date": "2026-10-05"
   }
  },
  {
   "name": "coo",
   "role": "C-suite \u00b7 operations",
   "latest": null
  },
  {
   "name": "courage",
   "role": "Scheduled jobs & checks",
   "latest": {
    "path": "AI-Drive/Agent-Output/courage/.watchtower-probe",
    "date": "2026-10-09"
   }
  },
  {
   "name": "cro",
   "role": "Chief Risk Officer \u2014 risk & compliance",
   "latest": null
  },
  {
   "name": "cto",
   "role": "C-suite \u00b7 technology",
   "latest": null
  },
  {
   "name": "daniel",
   "role": "Divorced Dads GM (Paperclip)",
   "latest": null
  },
  {
   "name": "dexter",
   "role": "Quantified researcher \u2014 metrics & telemetry",
   "latest": {
    "path": "AI-Drive/Agent-Output/dexter/metrics/spend-daily.csv",
    "date": "2026-10-08"
   }
  },
  {
   "name": "infinity",
   "role": "Infinity Brands",
   "latest": null
  },
  {
   "name": "inspector",
   "role": "Audits & inspection",
   "latest": {
    "path": "AI-Drive/Agent-Output/inspector/hindsight-dashboard-recon-2026-10-07.md",
    "date": "2026-10-07"
   }
  },
  {
   "name": "jean",
   "role": "Weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/jean/2026-10-11-weekly-score.md",
    "date": "2026-10-07"
   }
  },
  {
   "name": "joe",
   "role": "Joe the Farmer \u2014 TLF brand GM",
   "latest": null
  },
  {
   "name": "johnny",
   "role": "Weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/johnny/2026-10-07-weekly-score.md",
    "date": "2026-10-07"
   }
  },
  {
   "name": "lois",
   "role": "Ticker",
   "latest": null
  },
  {
   "name": "papa",
   "role": "Papa Prime \u2014 Papa Pasta brand GM",
   "latest": {
    "path": "AI-Drive/Agent-Output/papa/deep-dive-work/comment-verification.json",
    "date": "2026-10-06"
   }
  },
  {
   "name": "poppins",
   "role": "Family & personal CRM \u00b7 weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/poppins/2026-10-07-weekly-score.md",
    "date": "2026-10-07"
   }
  },
  {
   "name": "research",
   "role": "Research arm",
   "latest": {
    "path": "AI-Drive/Agent-Output/research/agent-sector-ledger.csv",
    "date": "2026-10-08"
   }
  },
  {
   "name": "reviewer",
   "role": "Code review",
   "latest": {
    "path": "AI-Drive/Agent-Output/reviewer/published.csv",
    "date": "2026-10-07"
   }
  },
  {
   "name": "scrooge",
   "role": "Personal finance & investments",
   "latest": {
    "path": "AI-Drive/Agent-Output/scrooge/weekly-score-2026-10-07.md",
    "date": "2026-10-07"
   }
  },
  {
   "name": "shadow",
   "role": "Restricted ops \u2014 OSINT & dark-web (local model)",
   "latest": null
  },
  {
   "name": "splinter",
   "role": "Personal family lead",
   "latest": {
    "path": "AI-Drive/Agent-Output/splinter/published.csv",
    "date": "2026-10-08"
   }
  },
  {
   "name": "stack-setup",
   "role": "Stack installs",
   "latest": {
    "path": "AI-Drive/Agent-Output/stack-setup/skills-ledger.md",
    "date": "2026-10-06"
   }
  },
  {
   "name": "storm",
   "role": "Home & environment \u00b7 weekly wheel",
   "latest": {
    "path": "AI-Drive/Agent-Output/storm/weekly-score-2026-10-07.md",
    "date": "2026-10-07"
   }
  },
  {
   "name": "targetpraks",
   "role": "\u2014",
   "latest": {
    "path": "AI-Drive/Agent-Output/targetpraks/github-public-audit/visibility-change-send.txt",
    "date": "2026-10-07"
   }
  },
  {
   "name": "xavier",
   "role": "X-Mansion cluster (predecessor)",
   "latest": {
    "path": "AI-Drive/Agent-Output/xavier/2026-10-07-weekly-score.md",
    "date": "2026-10-07"
   }
  }
 ],
 "system": {
  "launchd": {
   "jobs": [
    {
     "label": "com.maio.snappier-playlists",
     "pid": 948,
     "exit": 0
    },
    {
     "label": "com.maio.hiksemi-recover",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.keep-awake-guard",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.omlx-watchdog",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.wheel-poppins",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.maio-os-local",
     "pid": 26140,
     "exit": 0
    },
    {
     "label": "com.maio.copilot-mcp",
     "pid": 974,
     "exit": 0
    },
    {
     "label": "com.hermes.serve",
     "pid": 975,
     "exit": 0
    },
    {
     "label": "com.maio.wheel-xavier",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.deadman",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.maio-os-refresh",
     "pid": 50392,
     "exit": 0
    },
    {
     "label": "com.maio.qmd-refresh",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.brief-fallback",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.gamma-mcp",
     "pid": 2649,
     "exit": 0
    },
    {
     "label": "com.maio.cua-driver-supervisor",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.courage-backups",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.paperclip-briefing-collector",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.ollama-console",
     "pid": 986,
     "exit": 0
    },
    {
     "label": "com.maio.mount-nas",
     "pid": null,
     "exit": 0
    },
    {
     "label": "ai.hermes.gateway",
     "pid": 32600,
     "exit": 75
    },
    {
     "label": "com.maio.hermes-dashboard",
     "pid": 995,
     "exit": 0
    },
    {
     "label": "com.maio.wheel-johnny",
     "pid": null,
     "exit": 0
    },
    {
     "label": "ing.paperclip.paperclipai",
     "pid": 949,
     "exit": 0
    },
    {
     "label": "com.maio.docs-mcp",
     "pid": 956,
     "exit": 0
    },
    {
     "label": "com.maio.read-room",
     "pid": 959,
     "exit": 0
    },
    {
     "label": "com.maio.ok-vault-server",
     "pid": 2660,
     "exit": -15
    },
    {
     "label": "com.maio.composio-mcp",
     "pid": 981,
     "exit": 0
    },
    {
     "label": "com.maio.wheel-storm",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.google-health",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.wheel-scrooge",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.composio-finish-check",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.cloudflare-mcp",
     "pid": 960,
     "exit": 0
    },
    {
     "label": "com.maio.vault-agent",
     "pid": 964,
     "exit": 0
    },
    {
     "label": "com.maio.zztest",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.wheel-baymax",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.krea-mcp",
     "pid": 999,
     "exit": 0
    },
    {
     "label": "com.maio.watchtower",
     "pid": null,
     "exit": 0
    },
    {
     "label": "ai.omnigent.host",
     "pid": 954,
     "exit": 0
    },
    {
     "label": "com.maio.omlx-app",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.courage-health",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.todoist-mcp",
     "pid": 968,
     "exit": 0
    },
    {
     "label": "com.maio.pipedream-mcp",
     "pid": 970,
     "exit": 0
    },
    {
     "label": "com.maio.wheel-jean",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.browseruse-mcp",
     "pid": 982,
     "exit": 0
    },
    {
     "label": "com.maio.superhuman-mcp",
     "pid": 996,
     "exit": 0
    },
    {
     "label": "com.maio.meta-reap",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.snappier-server",
     "pid": 1002,
     "exit": 0
    },
    {
     "label": "com.maio.ok-vault-server-watchdog",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.agent-desktop-guard",
     "pid": 943,
     "exit": 0
    },
    {
     "label": "com.maio.magnific-mcp",
     "pid": 962,
     "exit": 0
    },
    {
     "label": "com.maio.gate-mcp",
     "pid": 978,
     "exit": 0
    },
    {
     "label": "com.maio.litellm-watchdog",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.stack-up",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.qmd-mcp",
     "pid": 990,
     "exit": 0
    },
    {
     "label": "com.maio.backup",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.courage-nightcheck",
     "pid": null,
     "exit": 0
    },
    {
     "label": "com.maio.keep-awake",
     "pid": 1001,
     "exit": 0
    },
    {
     "label": "com.maio.status-agent",
     "pid": 25181,
     "exit": -15
    }
   ],
   "counts": {
    "loaded": 58,
    "running": 29
   }
  },
  "docker": [
   {
    "name": "litellm-litellm-1",
    "status": "Up 9 hours (healthy)",
    "ports": "127.0.0.1:4000->4000/tcp"
   },
   {
    "name": "hindsight",
    "status": "Up 9 hours (healthy)",
    "ports": "127.0.0.1:8888->8888/tcp, 127.0.0.1:9999->9999/tcp"
   },
   {
    "name": "metamcp",
    "status": "Up 2 hours (healthy)",
    "ports": "127.0.0.1:12008->12008/tcp"
   },
   {
    "name": "litellm-litellm-redis-1",
    "status": "Up 9 hours (healthy)",
    "ports": "6379/tcp"
   },
   {
    "name": "constellation-dev-pg",
    "status": "Up 9 hours",
    "ports": "127.0.0.1:55440->5432/tcp"
   },
   {
    "name": "metamcp-pg",
    "status": "Up 9 hours (healthy)",
    "ports": "127.0.0.1:9433->5432/tcp"
   },
   {
    "name": "litellm-litellm-db-1",
    "status": "Up 9 hours",
    "ports": "5432/tcp"
   }
  ],
  "serves": {
   "routes": [
    {
     "url": "https://ricardos-mac-mini.taile9f837.ts.net:10000",
     "target": "http://127.0.0.1:3220"
    },
    {
     "url": "https://ricardos-mac-mini.taile9f837.ts.net",
     "target": "http://127.0.0.1:6767"
    },
    {
     "url": "https://ricardos-mac-mini.taile9f837.ts.net:8443",
     "target": "http://127.0.0.1:9110"
    },
    {
     "url": "https://ricardos-mac-mini.taile9f837.ts.net:8787",
     "target": "http://127.0.0.1:8787"
    },
    {
     "url": "https://ricardos-mac-mini.taile9f837.ts.net:8788",
     "target": "http://127.0.0.1:8788"
    },
    {
     "url": "https://ricardos-mac-mini.taile9f837.ts.net:9443",
     "target": "http://127.0.0.1:9111"
    }
   ],
   "count": 6
  },
  "kanban": {
   "board": "default",
   "counts": {
    "done": 109,
    "blocked": 3
   },
   "total": 112,
   "recent": [
    {
     "id": "t_176d3d6e",
     "title": "Vault: file 'Discord output formatting \u2014 fixed fleet-wide (2026-10-08)' to AI-Space/2.Automations-Skills/Reports/2026-10-08-discord-output-formatting-fixed-flee",
     "status": "done",
     "assignee": "beast"
    },
    {
     "id": "t_f9b740a8",
     "title": "Vault: file 'Gamma 5 \u2014 Fleet Integration & Connectors Report (2026-10-08)' to AI-Space/2.Automations-Skills/Reports/2026-10-08-gamma-5-fleet-integration-connect",
     "status": "done",
     "assignee": "beast"
    },
    {
     "id": "t_a06880c2",
     "title": "Vault fix: emoji-in-label link bug \u2014 correct 2 notes (Clickable-Vault-Links.md + Document-Publishing-Convention-2026-10-07.md) \u2014 rule-4 handoff from adrianna",
     "status": "done",
     "assignee": "beast"
    },
    {
     "id": "t_72e9fab8",
     "title": "Vault update: LLM Model Landscape Living Report \u2014 week 41 (2026-10-08) \u2014 rule-4 handoff from adrianna",
     "status": "done",
     "assignee": "beast"
    },
    {
     "id": "t_89bfb6b1",
     "title": "Vault update: LLM Model Landscape Living Report \u2014 week 41 (2026-10-08) \u2014 rule-4 handoff from adrianna",
     "status": "done",
     "assignee": "beast"
    },
    {
     "id": "t_9fdc8008",
     "title": "Vault: file 'Zoho Cliq \u2014 where Ricardo told Sales & Marketing to fill in the form (and that everything is to be filled out)' to Work/2.Automations-Skills/Report",
     "status": "done",
     "assignee": "beast"
    },
    {
     "id": "t_70d65b82",
     "title": "Vault: UPDATE Dahl Inference brief in place \u2014 add 'Alternatives' section to AI-Space/4.Research/2026-10-08-dahl-inference-inference-dahl-global-research-brief.m",
     "status": "done",
     "assignee": "beast"
    },
    {
     "id": "t_06dd7af3",
     "title": "Vault: append pending change-log entries to Vault-Lifecycle-Log (blocked on its OK CRDT conflict)",
     "status": "blocked",
     "assignee": "beast"
    },
    {
     "id": "t_7102467a",
     "title": "Vault change-log: append the constellation merge-status entry to Vault-Lifecycle-Log.md (needs OK-app conflict resolution)",
     "status": "blocked",
     "assignee": "beast"
    },
    {
     "id": "t_df6f85cb",
     "title": "Vault: file 'Orca vs Paseo \u2014 Review & Fleet Verdict' to AI-Space/4.Research/2026-10-08-orca-vs-paseo-review-fleet-verdict.md \u2014 rule-4 handoff from adrianna",
     "status": "done",
     "assignee": "beast"
    },
    {
     "id": "t_8d809b35",
     "title": "Vault: record constellation merge to main (b568786) \u2014 mark feat/enhancements merged in the Constellation notes",
     "status": "done",
     "assignee": "beast"
    },
    {
     "id": "t_dece22e8",
     "title": "Vault change-log: append the zoho per-person internal filing entry to Vault-Lifecycle-Log.md (needs OK-app conflict resolution)",
     "status": "blocked",
     "assignee": "beast"
    }
   ]
  },
  "tailnet": {
   "hostname": "ricardos-mac-mini.taile9f837.ts.net",
   "ip": "100.125.97.78"
  }
 },
 "prds": [
  {
   "title": "2026-10-08-constellation-enhancements-program-report",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/2026-10-08-constellation-enhancements-program-report.md",
   "date": "2026-10-08",
   "area": "Work"
  },
  {
   "title": "2026-10-07-constellation-enhancements-launch",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/2026-10-07-constellation-enhancements-launch.md",
   "date": "2026-10-08",
   "area": "Work"
  },
  {
   "title": "2026-10-07-fleet-publishing-workflow-v2-plan",
   "project": "Active",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/2026-10-07-fleet-publishing-workflow-v2-plan.md",
   "date": "2026-10-07",
   "area": "AI-Space"
  },
  {
   "title": "Constellation-Audit-2026-10-06",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Audit-2026-10-06.md",
   "date": "2026-10-07",
   "area": "Work"
  },
  {
   "title": "PRD-Maio-Task-Center-Improvements-2026-09-01",
   "project": "Archived",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/PRD-Maio-Task-Center-Improvements-2026-09-01.md",
   "date": "2026-10-07",
   "area": "AI-Space"
  },
  {
   "title": "PRD-Maio-Task-Center-v2-2026-09-01",
   "project": "Active",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/PRD-Maio-Task-Center-v2-2026-09-01.md",
   "date": "2026-10-07",
   "area": "AI-Space"
  },
  {
   "title": "PRD-Maio-Task-Center-2026-09-01",
   "project": "Archived",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/PRD-Maio-Task-Center-2026-09-01.md",
   "date": "2026-10-07",
   "area": "AI-Space"
  },
  {
   "title": "Anytype-Mirror-Plan-2026-08-05",
   "project": "Archived",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/Anytype-Mirror-Plan-2026-08-05.md",
   "date": "2026-10-07",
   "area": "AI-Space"
  },
  {
   "title": "Anytype-Template-Plan-2026-08-23",
   "project": "Active",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/Anytype-Template-Plan-2026-08-23.md",
   "date": "2026-10-07",
   "area": "AI-Space"
  },
  {
   "title": "Anytype-Template-Fix-2026-08-23",
   "project": "Active",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/Anytype-Template-Fix-2026-08-23.md",
   "date": "2026-10-07",
   "area": "AI-Space"
  },
  {
   "title": "PRD_v2_2026-09-08",
   "project": "Papa-Pasta-Store1-MasterSetup",
   "path": "Vault/Maio Hub/Work/3.PRD/Archived/Papa-Pasta-Store1-MasterSetup/PRD_v2_2026-09-08.md",
   "date": "2026-10-07",
   "area": "Work"
  },
  {
   "title": "PRD_v1_2026-09-08",
   "project": "Papa-Pasta-Store1-MasterSetup",
   "path": "Vault/Maio Hub/Work/3.PRD/Archived/Papa-Pasta-Store1-MasterSetup/PRD_v1_2026-09-08.md",
   "date": "2026-10-07",
   "area": "Work"
  },
  {
   "title": "PRD-Agent-Fleet-Cron-Automation-2026-08-29",
   "project": "Archived",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/PRD-Agent-Fleet-Cron-Automation-2026-08-29.md",
   "date": "2026-10-07",
   "area": "AI-Space"
  },
  {
   "title": "Code-Graph-Vault-Schema",
   "project": "Active",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/Code-Graph-Vault-Schema.md",
   "date": "2026-10-07",
   "area": "AI-Space"
  },
  {
   "title": "Constellation-Multi-Company-Plan-2026-10-01",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Multi-Company-Plan-2026-10-01.md",
   "date": "2026-10-06",
   "area": "Work"
  },
  {
   "title": "PRD-Beast-Vault-Keeper-Crons-2026-10-06",
   "project": "Active",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/PRD-Beast-Vault-Keeper-Crons-2026-10-06.md",
   "date": "2026-10-06",
   "area": "AI-Space"
  },
  {
   "title": "Constellation-Product-Audit-2026-09-30",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Product-Audit-2026-09-30.md",
   "date": "2026-10-01",
   "area": "Work"
  },
  {
   "title": "Constellation-MoA-Rulings-2026-09-17",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-MoA-Rulings-2026-09-17.md",
   "date": "2026-09-30",
   "area": "Work"
  },
  {
   "title": "2026-09-10 OpenWebUI Decommission",
   "project": "Archived",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/2026-09-10 OpenWebUI Decommission.md",
   "date": "2026-09-29",
   "area": "AI-Space"
  },
  {
   "title": "QwenPaw-Telegram-Topics-Brief-2026-09-28",
   "project": "Active",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/QwenPaw-Telegram-Topics-Brief-2026-09-28.md",
   "date": "2026-09-28",
   "area": "AI-Space"
  },
  {
   "title": "TLF-Zoho-Buildout-CSuite-Review-and-Decisions",
   "project": "TLF-Zoho-Buildout",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Zoho-Buildout/TLF-Zoho-Buildout-CSuite-Review-and-Decisions.md",
   "date": "2026-09-28",
   "area": "Work"
  },
  {
   "title": "TLF-Zoho-Buildout-PRD",
   "project": "TLF-Zoho-Buildout",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Zoho-Buildout/TLF-Zoho-Buildout-PRD.md",
   "date": "2026-09-28",
   "area": "Work"
  },
  {
   "title": "DD-QUICK-REFERENCE",
   "project": "Divorced-Dads",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Divorced-Dads/DD-QUICK-REFERENCE.md",
   "date": "2026-09-27",
   "area": "Work"
  },
  {
   "title": "DD-MARKET-INTEL",
   "project": "Divorced-Dads",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Divorced-Dads/DD-MARKET-INTEL.md",
   "date": "2026-09-27",
   "area": "Work"
  },
  {
   "title": "Papa-Pasta-Remaining-Brand-Marketing-Tasks",
   "project": "Papa Pasta",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Papa Pasta/Papa-Pasta-Remaining-Brand-Marketing-Tasks.md",
   "date": "2026-09-27",
   "area": "Work"
  },
  {
   "title": "Mr-Infinity-Cron-Architecture",
   "project": "Infinity-Brands-GM",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Infinity-Brands-GM/Mr-Infinity-Cron-Architecture.md",
   "date": "2026-09-27",
   "area": "Work"
  },
  {
   "title": "Magnific-Spaces-Flows-Research-2026-08-24",
   "project": "Active",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/Magnific-Spaces-Flows-Research-2026-08-24.md",
   "date": "2026-09-24",
   "area": "AI-Space"
  },
  {
   "title": "PRD",
   "project": "Papa-Pasta-Kitchen-Equipment-Sourcing",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Papa-Pasta-Kitchen-Equipment-Sourcing/PRD.md",
   "date": "2026-09-24",
   "area": "Work"
  },
  {
   "title": "The-Good-Stuff-Personal-Top-10",
   "project": "Active",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Good-Stuff-Personal-Top-10.md",
   "date": "2026-09-23",
   "area": "Work"
  },
  {
   "title": "Constellation-Instrument-Research-2026-09-17",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Instrument-Research-2026-09-17.md",
   "date": "2026-09-21",
   "area": "Work"
  },
  {
   "title": "Constellation-Verified-Findings-2026-09-17",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Verified-Findings-2026-09-17.md",
   "date": "2026-09-21",
   "area": "Work"
  },
  {
   "title": "Constellation-Scope-2026-09-16",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Scope-2026-09-16.md",
   "date": "2026-09-21",
   "area": "Work"
  },
  {
   "title": "Constellation-Build-Spec-2026-09-16",
   "project": "Constellation",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Build-Spec-2026-09-16.md",
   "date": "2026-09-21",
   "area": "Work"
  },
  {
   "title": "SunScout-Website-PRD-2026-09-15",
   "project": "SunScout",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/SunScout/SunScout-Website-PRD-2026-09-15.md",
   "date": "2026-09-16",
   "area": "Work"
  },
  {
   "title": "Divorced-Dads-Playlists",
   "project": "Divorced-Dads",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Divorced-Dads/Divorced-Dads-Playlists.md",
   "date": "2026-09-16",
   "area": "Work"
  },
  {
   "title": "SunScout-Web-App-System-PRD-2026-09-15",
   "project": "SunScout",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/SunScout/SunScout-Web-App-System-PRD-2026-09-15.md",
   "date": "2026-09-16",
   "area": "Work"
  },
  {
   "title": "PRD-v2.8-UI-Design-System",
   "project": "Quote-Program",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Quote-Program/PRD-v2.8-UI-Design-System.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "FluxFlow-Public-Data-Connectors",
   "project": "FluxFlow",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/FluxFlow/FluxFlow-Public-Data-Connectors.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "INF-MKT-Template-One-Master-Explained",
   "project": "Active",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/INF-MKT-Template-One-Master-Explained.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "PRD-Outside-In-Brand-Surface-Watchdog-2026-09-13",
   "project": "Active",
   "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/PRD-Outside-In-Brand-Surface-Watchdog-2026-09-13.md",
   "date": "2026-09-15",
   "area": "AI-Space"
  },
  {
   "title": "TLF-App-INFX-Feedback-Report",
   "project": "Active",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/TLF-App-INFX-Feedback-Report.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "CHANGE-LOG-v23",
   "project": "TLF-Franchisee-Model-Audit",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/CHANGE-LOG-v23.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "CHANGELOG-v26",
   "project": "TLF-Franchisee-Model-Audit",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/CHANGELOG-v26.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "CHANGELOG-v25",
   "project": "TLF-Franchisee-Model-Audit",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/CHANGELOG-v25.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "CHANGELOG-v24",
   "project": "TLF-Franchisee-Model-Audit",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/CHANGELOG-v24.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "audit_A_formula_consistency",
   "project": "TLF-Franchisee-Model-Audit",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/audit_A_formula_consistency.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "_folder",
   "project": "TLF-Franchisee-Model-Audit",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/_folder.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "INF-KPI-Compliance-Enforcement-Sep-2026",
   "project": "Infinity-Brands-GM",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Infinity-Brands-GM/INF-KPI-Compliance-Enforcement-Sep-2026.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "TLF-Joe-Farmer-Agent-PRD",
   "project": "The-Local-Farmer",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Joe-Farmer-Agent-PRD.md",
   "date": "2026-09-15",
   "area": "Work"
  },
  {
   "title": "voice",
   "project": "Company-Brain",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Loxbox/Company-Brain/voice.md",
   "date": "2026-09-14",
   "area": "Work"
  },
  {
   "title": "offer",
   "project": "Company-Brain",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Loxbox/Company-Brain/offer.md",
   "date": "2026-09-14",
   "area": "Work"
  },
  {
   "title": "company",
   "project": "Company-Brain",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Loxbox/Company-Brain/company.md",
   "date": "2026-09-14",
   "area": "Work"
  },
  {
   "title": "customer",
   "project": "Company-Brain",
   "path": "Vault/Maio Hub/Work/3.PRD/Active/Loxbox/Company-Brain/customer.md",
   "date": "2026-09-14",
   "area": "Work"
  },
  {
   "title": "PRD-SECTION-DESIGN.md",
   "project": "Papa Pasta",
   "path": "AI-Drive/AI-Space/Work/Papa Pasta/Store Design/PRD/PRD-SECTION-DESIGN.md",
   "date": "2026-09-01",
   "area": "disk scan"
  },
  {
   "title": "PRD_FEATURE.md",
   "project": "esoteric-command",
   "path": "DevMini/esoteric-command/PRD_FEATURE.md",
   "date": "2026-08-21",
   "area": "disk scan"
  },
  {
   "title": "PRD.md",
   "project": "chromacommand-platform",
   "path": "DevMini/chromacommand-platform/PRD.md",
   "date": "2026-07-24",
   "area": "disk scan"
  },
  {
   "title": "PRD_v2.md",
   "project": "sunscout",
   "path": "DevMini/sunscout/docs/PRD_v2.md",
   "date": "2026-07-24",
   "area": "disk scan"
  }
 ],
 "enriched": {
  "vaultPrds": [
   {
    "title": "2026-10-08-constellation-enhancements-program-report",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/2026-10-08-constellation-enhancements-program-report.md",
    "date": "2026-10-08"
   },
   {
    "title": "2026-10-07-constellation-enhancements-launch",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/2026-10-07-constellation-enhancements-launch.md",
    "date": "2026-10-08"
   },
   {
    "title": "2026-10-07-fleet-publishing-workflow-v2-plan",
    "project": "Active",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/2026-10-07-fleet-publishing-workflow-v2-plan.md",
    "date": "2026-10-07"
   },
   {
    "title": "Constellation-Audit-2026-10-06",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Audit-2026-10-06.md",
    "date": "2026-10-07"
   },
   {
    "title": "PRD-Maio-Task-Center-Improvements-2026-09-01",
    "project": "Archived",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/PRD-Maio-Task-Center-Improvements-2026-09-01.md",
    "date": "2026-10-07"
   },
   {
    "title": "PRD-Maio-Task-Center-v2-2026-09-01",
    "project": "Active",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/PRD-Maio-Task-Center-v2-2026-09-01.md",
    "date": "2026-10-07"
   },
   {
    "title": "PRD-Maio-Task-Center-2026-09-01",
    "project": "Archived",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/PRD-Maio-Task-Center-2026-09-01.md",
    "date": "2026-10-07"
   },
   {
    "title": "Anytype-Mirror-Plan-2026-08-05",
    "project": "Archived",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/Anytype-Mirror-Plan-2026-08-05.md",
    "date": "2026-10-07"
   },
   {
    "title": "Anytype-Template-Plan-2026-08-23",
    "project": "Active",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/Anytype-Template-Plan-2026-08-23.md",
    "date": "2026-10-07"
   },
   {
    "title": "Anytype-Template-Fix-2026-08-23",
    "project": "Active",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/Anytype-Template-Fix-2026-08-23.md",
    "date": "2026-10-07"
   },
   {
    "title": "PRD_v2_2026-09-08",
    "project": "Papa-Pasta-Store1-MasterSetup",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Archived/Papa-Pasta-Store1-MasterSetup/PRD_v2_2026-09-08.md",
    "date": "2026-10-07"
   },
   {
    "title": "PRD_v1_2026-09-08",
    "project": "Papa-Pasta-Store1-MasterSetup",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Archived/Papa-Pasta-Store1-MasterSetup/PRD_v1_2026-09-08.md",
    "date": "2026-10-07"
   },
   {
    "title": "PRD-Agent-Fleet-Cron-Automation-2026-08-29",
    "project": "Archived",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/PRD-Agent-Fleet-Cron-Automation-2026-08-29.md",
    "date": "2026-10-07"
   },
   {
    "title": "Code-Graph-Vault-Schema",
    "project": "Active",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/Code-Graph-Vault-Schema.md",
    "date": "2026-10-07"
   },
   {
    "title": "Constellation-Multi-Company-Plan-2026-10-01",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Multi-Company-Plan-2026-10-01.md",
    "date": "2026-10-06"
   },
   {
    "title": "PRD-Beast-Vault-Keeper-Crons-2026-10-06",
    "project": "Active",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/PRD-Beast-Vault-Keeper-Crons-2026-10-06.md",
    "date": "2026-10-06"
   },
   {
    "title": "Constellation-Product-Audit-2026-09-30",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Product-Audit-2026-09-30.md",
    "date": "2026-10-01"
   },
   {
    "title": "Constellation-MoA-Rulings-2026-09-17",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-MoA-Rulings-2026-09-17.md",
    "date": "2026-09-30"
   },
   {
    "title": "2026-09-10 OpenWebUI Decommission",
    "project": "Archived",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Archived/2026-09-10 OpenWebUI Decommission.md",
    "date": "2026-09-29"
   },
   {
    "title": "QwenPaw-Telegram-Topics-Brief-2026-09-28",
    "project": "Active",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/QwenPaw-Telegram-Topics-Brief-2026-09-28.md",
    "date": "2026-09-28"
   },
   {
    "title": "TLF-Zoho-Buildout-CSuite-Review-and-Decisions",
    "project": "TLF-Zoho-Buildout",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Zoho-Buildout/TLF-Zoho-Buildout-CSuite-Review-and-Decisions.md",
    "date": "2026-09-28"
   },
   {
    "title": "TLF-Zoho-Buildout-PRD",
    "project": "TLF-Zoho-Buildout",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Zoho-Buildout/TLF-Zoho-Buildout-PRD.md",
    "date": "2026-09-28"
   },
   {
    "title": "DD-QUICK-REFERENCE",
    "project": "Divorced-Dads",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Divorced-Dads/DD-QUICK-REFERENCE.md",
    "date": "2026-09-27"
   },
   {
    "title": "DD-MARKET-INTEL",
    "project": "Divorced-Dads",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Divorced-Dads/DD-MARKET-INTEL.md",
    "date": "2026-09-27"
   },
   {
    "title": "Papa-Pasta-Remaining-Brand-Marketing-Tasks",
    "project": "Papa Pasta",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Papa Pasta/Papa-Pasta-Remaining-Brand-Marketing-Tasks.md",
    "date": "2026-09-27"
   },
   {
    "title": "Mr-Infinity-Cron-Architecture",
    "project": "Infinity-Brands-GM",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Infinity-Brands-GM/Mr-Infinity-Cron-Architecture.md",
    "date": "2026-09-27"
   },
   {
    "title": "Magnific-Spaces-Flows-Research-2026-08-24",
    "project": "Active",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/Magnific-Spaces-Flows-Research-2026-08-24.md",
    "date": "2026-09-24"
   },
   {
    "title": "PRD",
    "project": "Papa-Pasta-Kitchen-Equipment-Sourcing",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Papa-Pasta-Kitchen-Equipment-Sourcing/PRD.md",
    "date": "2026-09-24"
   },
   {
    "title": "The-Good-Stuff-Personal-Top-10",
    "project": "Active",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Good-Stuff-Personal-Top-10.md",
    "date": "2026-09-23"
   },
   {
    "title": "Constellation-Instrument-Research-2026-09-17",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Instrument-Research-2026-09-17.md",
    "date": "2026-09-21"
   },
   {
    "title": "Constellation-Verified-Findings-2026-09-17",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Verified-Findings-2026-09-17.md",
    "date": "2026-09-21"
   },
   {
    "title": "Constellation-Scope-2026-09-16",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Scope-2026-09-16.md",
    "date": "2026-09-21"
   },
   {
    "title": "Constellation-Build-Spec-2026-09-16",
    "project": "Constellation",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Constellation/Constellation-Build-Spec-2026-09-16.md",
    "date": "2026-09-21"
   },
   {
    "title": "SunScout-Website-PRD-2026-09-15",
    "project": "SunScout",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/SunScout/SunScout-Website-PRD-2026-09-15.md",
    "date": "2026-09-16"
   },
   {
    "title": "Divorced-Dads-Playlists",
    "project": "Divorced-Dads",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Divorced-Dads/Divorced-Dads-Playlists.md",
    "date": "2026-09-16"
   },
   {
    "title": "SunScout-Web-App-System-PRD-2026-09-15",
    "project": "SunScout",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/SunScout/SunScout-Web-App-System-PRD-2026-09-15.md",
    "date": "2026-09-16"
   },
   {
    "title": "PRD-v2.8-UI-Design-System",
    "project": "Quote-Program",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Quote-Program/PRD-v2.8-UI-Design-System.md",
    "date": "2026-09-15"
   },
   {
    "title": "FluxFlow-Public-Data-Connectors",
    "project": "FluxFlow",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/FluxFlow/FluxFlow-Public-Data-Connectors.md",
    "date": "2026-09-15"
   },
   {
    "title": "INF-MKT-Template-One-Master-Explained",
    "project": "Active",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/INF-MKT-Template-One-Master-Explained.md",
    "date": "2026-09-15"
   },
   {
    "title": "PRD-Outside-In-Brand-Surface-Watchdog-2026-09-13",
    "project": "Active",
    "area": "AI-Space",
    "path": "Vault/Maio Hub/AI-Space/3.PRD/Active/PRD-Outside-In-Brand-Surface-Watchdog-2026-09-13.md",
    "date": "2026-09-15"
   },
   {
    "title": "TLF-App-INFX-Feedback-Report",
    "project": "Active",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/TLF-App-INFX-Feedback-Report.md",
    "date": "2026-09-15"
   },
   {
    "title": "CHANGE-LOG-v23",
    "project": "TLF-Franchisee-Model-Audit",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/CHANGE-LOG-v23.md",
    "date": "2026-09-15"
   },
   {
    "title": "CHANGELOG-v26",
    "project": "TLF-Franchisee-Model-Audit",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/CHANGELOG-v26.md",
    "date": "2026-09-15"
   },
   {
    "title": "CHANGELOG-v25",
    "project": "TLF-Franchisee-Model-Audit",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/CHANGELOG-v25.md",
    "date": "2026-09-15"
   },
   {
    "title": "CHANGELOG-v24",
    "project": "TLF-Franchisee-Model-Audit",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/CHANGELOG-v24.md",
    "date": "2026-09-15"
   },
   {
    "title": "audit_A_formula_consistency",
    "project": "TLF-Franchisee-Model-Audit",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/audit_A_formula_consistency.md",
    "date": "2026-09-15"
   },
   {
    "title": "_folder",
    "project": "TLF-Franchisee-Model-Audit",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Franchisee-Model-Audit/_folder.md",
    "date": "2026-09-15"
   },
   {
    "title": "INF-KPI-Compliance-Enforcement-Sep-2026",
    "project": "Infinity-Brands-GM",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Infinity-Brands-GM/INF-KPI-Compliance-Enforcement-Sep-2026.md",
    "date": "2026-09-15"
   },
   {
    "title": "TLF-Joe-Farmer-Agent-PRD",
    "project": "The-Local-Farmer",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/The-Local-Farmer/TLF-Joe-Farmer-Agent-PRD.md",
    "date": "2026-09-15"
   },
   {
    "title": "voice",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Loxbox/Company-Brain/voice.md",
    "date": "2026-09-14"
   },
   {
    "title": "offer",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Loxbox/Company-Brain/offer.md",
    "date": "2026-09-14"
   },
   {
    "title": "company",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Loxbox/Company-Brain/company.md",
    "date": "2026-09-14"
   },
   {
    "title": "customer",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/Loxbox/Company-Brain/customer.md",
    "date": "2026-09-14"
   },
   {
    "title": "voice",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/ACDC-Dynamics/Company-Brain/voice.md",
    "date": "2026-09-14"
   },
   {
    "title": "company",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/ACDC-Dynamics/Company-Brain/company.md",
    "date": "2026-09-14"
   },
   {
    "title": "offer",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/ACDC-Dynamics/Company-Brain/offer.md",
    "date": "2026-09-14"
   },
   {
    "title": "customer",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/ACDC-Dynamics/Company-Brain/customer.md",
    "date": "2026-09-14"
   },
   {
    "title": "customer",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/INFX-Labs/Company-Brain/customer.md",
    "date": "2026-09-14"
   },
   {
    "title": "company",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/INFX-Labs/Company-Brain/company.md",
    "date": "2026-09-14"
   },
   {
    "title": "voice",
    "project": "Company-Brain",
    "area": "Work",
    "path": "Vault/Maio Hub/Work/3.PRD/Active/INFX-Labs/Company-Brain/voice.md",
    "date": "2026-09-14"
   }
  ],
  "roles": {
   "jarvis": "AI Space Orchestrator \u2014 handles everything that isn't clearly Work or Personal",
   "atlas": "Research (Tier-1) \u2014 deep research, benchmarks, vendor evaluation",
   "archie": "Architecture specialist \u2014 system and solution architecture",
   "shadow": "Restricted-Ops specialist \u2014 OSINT, dark-web research; runs on the local model",
   "echo": "Comms (Tier-1) \u2014 briefs, summaries, comms drafting",
   "keeper": "Machine ops (Tier-1) \u2014 launchd, gateways, backups, host hardening",
   "forge": "Code and repos \u2014 builds, PRs, code review",
   "beacon": "Monitoring (Tier-1) \u2014 watchers, alerts, watchdog cron",
   "ai space": "JARVIS",
   "work": "Warren W",
   "personal": "Poppi P"
  },
  "ventures": [
   {
    "name": "Papa Pasta",
    "sector": "QSR Franchise \u2014 pasta",
    "status": "Active Development",
    "priority": "1 \u2014 \"100% my main priority\""
   },
   {
    "name": "The Local Farmer",
    "sector": "Farm / Supply, micro-franchise",
    "status": "Active",
    "priority": "2"
   },
   {
    "name": "Divorced Dads",
    "sector": "App for Divorced Men / Family Law Tech",
    "status": "Active Development",
    "priority": "3"
   },
   {
    "name": "Infinity Brands",
    "sector": "Brand / Portfolio Company (HQ)",
    "status": "Active",
    "priority": "4"
   },
   {
    "name": "INFX Solutions",
    "sector": "Zoho Implementation / Business Digitization",
    "status": "Active",
    "priority": "5"
   },
   {
    "name": "INFX Media",
    "sector": "Media / Marketing",
    "status": "Active Development",
    "priority": "6"
   },
   {
    "name": "INFX Labs",
    "sector": "Software Development House",
    "status": "Active",
    "priority": "6"
   },
   {
    "name": "FluxFlow",
    "sector": "ETL + Agentic AI for Business Tools",
    "status": "Active Development",
    "priority": "6"
   },
   {
    "name": "ChromaCommand",
    "sector": "RGB / digital menu / audio for the Papa Pasta network",
    "status": "Active Development",
    "priority": "6"
   },
   {
    "name": "SunScout",
    "sector": "Beach Convenience App (may become BeachScout)",
    "status": "Active Development",
    "priority": "6"
   },
   {
    "name": "Loxbox",
    "sector": "TBD (Greek market)",
    "status": "Fundraising",
    "priority": "6"
   },
   {
    "name": "Soul Hotel",
    "sector": "Hospitality / Apartment Hotel, Rhodes, Greece",
    "status": "Concept",
    "priority": "7"
   },
   {
    "name": "ACDC Express",
    "sector": "Electrical Retail / Franchise",
    "status": "Active",
    "priority": "7"
   }
  ],
  "enrichedWhat": {},
  "soulFound": true,
  "mergedAt": "2026-10-08T22:45:05Z"
 },
 "summary": {
  "projects": 57,
  "prds": 57,
  "stackLive": 12,
  "stackTotal": 12,
  "devOnline": 0,
  "devTotal": 10,
  "reports": 24,
  "roster": 34,
  "launchdLoaded": 58,
  "dockerUp": 7,
  "libraryPublic": 17,
  "libraryInternal": 200,
  "docs": 137
 },
 "library": {
  "public": [
   {
    "title": "Bank Funding Explained \u2014 the shapes of money, and what each one costs",
    "url": "bank-funding-explained.html",
    "dir": "bank-funding-explained.html",
    "date": "2026-10-08",
    "kb": 43
   },
   {
    "title": "Zoho Cliq \u2014 Ricardo's instruction to Sales &amp; Marketing: fill in the form, everything filled out, or written warnings",
    "url": "cliq-sales-marketing-fill-form-order.html",
    "dir": "cliq-sales-marketing-fill-form-order.html",
    "date": "2026-10-08",
    "kb": 27
   },
   {
    "title": "Hudaco Industries (JSE:HDC) \u2014 Company Analysis \u00b7 8 Oct 2026",
    "url": "hudaco-jse-hdc-company-analysis.html",
    "dir": "hudaco-jse-hdc-company-analysis.html",
    "date": "2026-10-08",
    "kb": 28
   },
   {
    "title": "Zoho Projects \u2014 Programme Health Review \u00b7 October 2026",
    "url": "zoho-projects-review-2026-10-08.html",
    "dir": "zoho-projects-review-2026-10-08.html",
    "date": "2026-10-08",
    "kb": 13
   },
   {
    "title": "The Maio Cosmos \u2014 Five Charts, One Sky",
    "url": "maio-cosmos/",
    "dir": "maio-cosmos",
    "date": "2026-09-26",
    "kb": 605
   },
   {
    "title": "Maio Cosmos \u2014 UK &amp; Europe",
    "url": "maio-cosmos-europe/",
    "dir": "maio-cosmos-europe",
    "date": "2026-09-26",
    "kb": 473
   },
   {
    "title": "Breastfeeding \u2014 a guide from the first days through the first year",
    "url": "breastfeeding-guide/",
    "dir": "breastfeeding-guide",
    "date": "2026-09-24",
    "kb": 257
   },
   {
    "title": "The Best-Town Explorer \u2014 Where in the World",
    "url": "best-town/",
    "dir": "best-town",
    "date": "2026-09-20",
    "kb": 659
   },
   {
    "title": "\ud83c\udf31 Welgemoed Garden Plan \u2014 Ricardo & Julie",
    "url": "garden-plan/",
    "dir": "garden-plan",
    "date": "2026-09-20",
    "kb": 44
   },
   {
    "title": "Ricardo &amp; Julie \u2014 Written in the Stars",
    "url": "rj-cosmos/",
    "dir": "rj-cosmos",
    "date": "2026-09-20",
    "kb": 26
   },
   {
    "title": "The Harvest File \u2014 The Local Farmer VIP Recipe Book \u00b7 Concept & Marketing Pack",
    "url": "tlf-harvest-file.html",
    "dir": "tlf-harvest-file.html",
    "date": "2026-09-20",
    "kb": 51
   },
   {
    "title": "Julie &mdash; The Charts of a Life",
    "url": "julie-charts/",
    "dir": "julie-charts",
    "date": "2026-09-12",
    "kb": 64
   },
   {
    "title": "Ricardo &mdash; The Charts of a Life",
    "url": "ricardo-charts/",
    "dir": "ricardo-charts",
    "date": "2026-09-12",
    "kb": 61
   },
   {
    "title": "Soul Hotel \u2014 Kalithea, Rhodes \u00b7 Interactive 3D Concept",
    "url": "soul-hotel/",
    "dir": "soul-hotel",
    "date": "2026-09-12",
    "kb": 13
   },
   {
    "title": "Ricardo Maio \u2014 Live Projects Dashboard",
    "url": "index.html",
    "dir": "index.html",
    "date": "2026-09-11",
    "kb": 25
   },
   {
    "title": "Maio Hub Jump",
    "url": "jump.html",
    "dir": "jump.html",
    "date": "2026-09-03",
    "kb": 1
   },
   {
    "title": "TLF App \u2014 INFX Solutions Team Feedback Report",
    "url": "tlf-feedback-report.html",
    "dir": "tlf-feedback-report.html",
    "date": "2026-07-24",
    "kb": 29
   }
  ],
  "counts": {
   "public": 17,
   "internal": 200,
   "docs": 137
  }
 }
};
